// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/myles-mcdonnell/sendmailserviceproxy/models"
)

// NewPostEmailParams creates a new PostEmailParams object
// with the default values initialized.
func NewPostEmailParams() *PostEmailParams {
	var ()
	return &PostEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostEmailParamsWithTimeout creates a new PostEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostEmailParamsWithTimeout(timeout time.Duration) *PostEmailParams {
	var ()
	return &PostEmailParams{

		timeout: timeout,
	}
}

// NewPostEmailParamsWithContext creates a new PostEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostEmailParamsWithContext(ctx context.Context) *PostEmailParams {
	var ()
	return &PostEmailParams{

		Context: ctx,
	}
}

// NewPostEmailParamsWithHTTPClient creates a new PostEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostEmailParamsWithHTTPClient(client *http.Client) *PostEmailParams {
	var ()
	return &PostEmailParams{
		HTTPClient: client,
	}
}

/*PostEmailParams contains all the parameters to send to the API endpoint
for the post email operation typically these are written to a http.Request
*/
type PostEmailParams struct {

	/*Email
	  Email to send

	*/
	Email *models.Email

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post email params
func (o *PostEmailParams) WithTimeout(timeout time.Duration) *PostEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post email params
func (o *PostEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post email params
func (o *PostEmailParams) WithContext(ctx context.Context) *PostEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post email params
func (o *PostEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post email params
func (o *PostEmailParams) WithHTTPClient(client *http.Client) *PostEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post email params
func (o *PostEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the post email params
func (o *PostEmailParams) WithEmail(email *models.Email) *PostEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the post email params
func (o *PostEmailParams) SetEmail(email *models.Email) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *PostEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Email == nil {
		o.Email = new(models.Email)
	}

	if err := r.SetBodyParam(o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
