// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/myles-mcdonnell/sendmailserviceproxy/models"
)

// PostEmailReader is a Reader for the PostEmail structure.
type PostEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostEmailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostEmailOK creates a PostEmailOK with default headers values
func NewPostEmailOK() *PostEmailOK {
	return &PostEmailOK{}
}

/*PostEmailOK handles this case with default header values.

Email forwarded successfully
*/
type PostEmailOK struct {
}

func (o *PostEmailOK) Error() string {
	return fmt.Sprintf("[POST /email][%d] postEmailOK ", 200)
}

func (o *PostEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailUnauthorized creates a PostEmailUnauthorized with default headers values
func NewPostEmailUnauthorized() *PostEmailUnauthorized {
	return &PostEmailUnauthorized{}
}

/*PostEmailUnauthorized handles this case with default header values.

unauthorised
*/
type PostEmailUnauthorized struct {
}

func (o *PostEmailUnauthorized) Error() string {
	return fmt.Sprintf("[POST /email][%d] postEmailUnauthorized ", 401)
}

func (o *PostEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailDefault creates a PostEmailDefault with default headers values
func NewPostEmailDefault(code int) *PostEmailDefault {
	return &PostEmailDefault{
		_statusCode: code,
	}
}

/*PostEmailDefault handles this case with default header values.

generic error response
*/
type PostEmailDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// Code gets the status code for the post email default response
func (o *PostEmailDefault) Code() int {
	return o._statusCode
}

func (o *PostEmailDefault) Error() string {
	return fmt.Sprintf("[POST /email][%d] PostEmail default  %+v", o._statusCode, o.Payload)
}

func (o *PostEmailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
